# Generated by Django 4.1 on 2022-09-06 06:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KurulusUlke', django_countries.fields.CountryField(max_length=2)),
                ('KurulusUrl', models.URLField()),
                ('KurukusCalisanSayi', models.IntegerField()),
            ],
        ),
    ]
