# Generated by Django 4.1 on 2022-09-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurulus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurulus',
            name='KurulusTuru',
            field=models.CharField(choices=[('SH', 'Sahsi'), ('STK', 'STK'), ('KO', 'KOBI'), ('BI', 'BI')], default='SH', max_length=10),
        ),
    ]
