# Generated by Django 4.1 on 2022-09-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurulus', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
